### ISSUE TITLE
Do maigw addresses expire?

### ISSUE THREAD

**Issue by Raytle** [j256/mailgw#6]
Assuming they don't expire, I suggest you add something like...

"Mailgw provides a free anti-spam-mail service to help you take control over your email. With your Mailgw account, you can give out a separate email address to every company which asks you for one. **Unlike many of our competitors, email addresses you create on Mailgw last indefinitely (they don't expire).**"

to 

https://mailgw.com/

**Comment by j256** [comment]
If you look at edit address page you see a lot of expiration options:

     Delete this address after ____  more messages or after this time: _______

Does this work?

**Comment by Raytle** [comment]
> Does this work?

Yes. That works. Thanks.
