### ISSUE TITLE
How does one use Mailgw's auto-create feature?

### ISSUE THREAD

**Issue by Raytle** [j256/mailgw#7]
>> I would like the ability to create a disposable email on the fly *without* needing to login.

> Other's have mentioned this.  Mailgw does have a auto-create feature but you need to confirm the creation.

Like the title of this issue asks: how does one use Mailgw's auto-create feature?

**Comment by j256** [comment]
Yeah the documentation is a bit lacking.  On the account edit page is the following:

Do you want addresses to be auto-created? With this enabled, mail to unknown addresses will be held and a notification sent to your email. This means you do not have to create addresses beforehand. Yes  No 

Does that help?

**Comment by j256** [comment]
Btw this would be more appropriate on the "Discussions" page as opposed to it being an "issue".

**Comment by Raytle** [comment]
> Does that help?

Yes.

> Btw this would be more appropriate on the "Discussions" page as opposed to it being an "issue".

You are right. I should have placed it  on the "Discussions" page.
