### ISSUE TITLE
adding tooltips to mailgw would make it easier to use

### ISSUE THREAD

**Issue by Raytle** [j256/mailgw#8]
I suggest you add [tooltips](https://www.nngroup.com/articles/tooltip-guidelines/) to Mailgw. For example, I think ["Del" and "Mail"](https://i.imgur.com/MJSrHPy.png) would benefit from tooltips.

I suppose the tooltips might be:

1. "Click on this to delete this email address. Don't worry, even if you confirm deletion of this email you will have the ability to undelete this email address for 365 days (a whole year)." 
3. "Click on this to send an email from this email address.

**Comment by j256** [comment]
Good idea as long as it doesn't make the page much wider.  Can you provide some CSS or javascript to accomplish this?

**Comment by Raytle** [comment]
> Good idea as long as it doesn't make the page much wider. 

I agree.


> Can you provide some CSS or javascript to accomplish this?

Sorry. No. I'm not a programmer.

**Comment by j256** [comment]
I've added more link titles.  How does it look?  I found some good tooltip CSS but it seems a bit over kill.

![image](https://user-images.githubusercontent.com/1749962/124679124-e21b5b80-de91-11eb-9088-0a8be6605809.png)

**Comment by Raytle** [comment]
> I've added more link titles. How does it look? 

I like that much better!

> I found some good tooltip CSS but it seems a bit over kill.

I think what you have added suffices. In other words, I think it gets the job done. 

Personally, instead of date created, I would prefer something like, "Created" with the following sorts of values: 4 days ago, 5 months ago, 2 years and 3 months ago, etc. But that's a very minor quibble.

**Comment by j256** [comment]
Good idea.  Done.  I've changed the created and the last-used to be a word based interval.  There are some time zone issues which make the first day a bit wonky.

**Comment by Raytle** [comment]
> There are some time zone issues which make the first day a bit wonky.

That seems like it would have no effect on, "Created about 2 hours ago" or "Created about 7 hours ago". But if it does, for, say, times that are—I suppose—24 hours or less your code might display something like, "Created within the last 24 hours."

Of course, I suppose precision is not very important for this. Users likely want to know something, "Oh, that's the email I created earlier today vs that's the email I created over 3 years ago" not "Oh, that's the email I created 3 hours and 12 minutes ago vs that's the email I created 4 hours and 27 minutes ago."
