### ISSUE TITLE
Creating disposable email addresses "on the fly"

### ISSUE THREAD

**Issue by Raytle** [j256/mailgw#9]
>> I liked the ability to create an email such as...
>> ibm.20.yek@spamgourmet.com

> I think that this is possible given the 3 periods.  

Sure. That's what I figured.

> I initially was worried that folks would create email addresses on your behalf 

It happened to me a dozen or so times on Spamgourmet: maybe once every year or two. It was notable but barely annoying compared to the very welcome "handiness" (usefulness) of being able to create a new disposable email address "on the fly" as I was signing up for a  user name and password on a new website.

When signing up on www.foo.com I would simply—essentially although not precisely—type something like "foo.2.yek@spamgourmet.com" where...

1. foo = website name, and
2. the number "2"= number of email messages to receive, and
3. yek@spamgourmet.com = the "root" of my spamgourmet.com email addresses.

Actually, precisely, I normally used "recursor.net" instead of "spamgourmet.com" because "recursor.net"—one of the domains owned by Spamgourmet—presumably would seem innocuous to any person who happened to glance at it, whereas "spamgourmet.com" would presumably seem suspicious.

> and then send you spam but they would need to know your original email in which case why bother.  

As I indicated above, once every year or two, I guess some spammer "messed up" their spambot and did send a message to one of my Spamgourmet disposable email addresses. But I presume they did so inadvertently (due to their own incompetence).

Here's an analogy for you: people injure themselves—and even die—walking up and down stairs. But stairs are commonly used because, of course, their benefits far outweigh the detriments.

> Obviously you would need to send mail from one of the emails on your account for this to be triggered

As I indicated above, that's **not** how it works on Spamgourmet.

If you wanted to error on the side of caution, I suppose you might do the following. The very first time Mailgw were to send a user an email from a "non-extant Mailgw disposable email address" you might send the user the actual email (that, say, Amazon.com or eBay.com had presumably sent to the user) as well as a second email message (a "safety email") with a "one-click confirmation" by which I mean, the second email message might have the user click on something such as, 

"We assume you probably created the following email address...

**FOO@gwmail.com** 

when, for example, you recently signed up for a new account on a new website. However, in the extremely unlikely event that, for example, a bot is sending spam to you using FOO@gwmail.com then please click on...

"This is spam! I don't want to receive messages which are sent to FOO@gwmail.com."

I'll be blunt: trying to create 100% secure products often leads engineers to make bad choices. No, I don't want a bridge to collapse. But a 99.99966% secure bridge for half the price is a almost always a better deal than a 99.99999% secure bridge which costs twice the price of the "vulnerable" bridge.

**Comment by j256** [comment]
> The very first time Mailgw were to send a user an email from a "non-extant Mailgw disposable email address" you might send the user the actual email (that, say, Amazon.com or eBay.com had presumably sent to the user) 

This is precisely how auto-create message work although without the need to send the "foo.2.yek@..." email.  You didn't try it out?

**Comment by Raytle** [comment]
Oh sorry. Now I see. Thanks.
